# detect operating system
if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
  message(STATUS "Target OS: Windows")
  add_compile_definitions(USE_PLATFORM_WINDOWS)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  message(STATUS "Target OS: Linux")
  add_compile_definitions(USE_PLATFORM_LINUX)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
  message(STATUS "Target OS: MacOs")
  add_compile_definitions(USE_PLATFORM_MACOS)
else()
  message(FATAL_ERROR "Target OS: Unknown")
endif()
